version: '3.8'

services:
  automatedpostgres:
    build:
      context: ..
      dockerfile: database/Dockerfile
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../sql:/sql
      - ../helperScripts:/helperScripts/
      - ../weather:/jsonfiles
    networks:
      - pgnetwork
    ports:
      - "${POSTGRES_PORT}:5432"

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./pgpass:/pgpass
      - ./servers.json:/pgadmin4/servers.json
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      - pgnetwork
    ports:
      - "5050:80"

volumes:
  postgres-data:
  pgadmin-data:


networks:
  pgnetwork:
    external: true
